# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "micro-integrator.fullname" . }}-mi-integrator
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "micro-integrator.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.wso2.deployment.mi.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.wso2.deployment.mi.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.wso2.deployment.mi.strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: {{ include "micro-integrator.fullname" . }}
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum.am.conf: {{ include (print $.Template.BasePath "/integrator/wso2mi-conf.yaml") . | sha256sum }}
      labels:
        deployment: {{ include "micro-integrator.fullname" . }}
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: wso2micro-integrator
{{- include "image" (dict "Values" .Values "deployment" .Values.wso2.deployment.mi) | indent 10 }}
          {{- if .Values.wso2.deployment.mi.synapseTest.enabled }}
          args:
            - "-DsynapseTest=true"
          {{- end }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 8290
            initialDelaySeconds: {{ .Values.wso2.deployment.mi.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.mi.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9201
            initialDelaySeconds: {{ .Values.wso2.deployment.mi.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.mi.readinessProbe.periodSeconds }}
          resources:
            requests:
              memory: {{ .Values.wso2.deployment.mi.resources.requests.memory }}
              cpu: {{ .Values.wso2.deployment.mi.resources.requests.cpu }}
            limits:
              memory: {{ .Values.wso2.deployment.mi.resources.limits.memory }}
              cpu: {{ .Values.wso2.deployment.mi.resources.limits.cpu }}
          imagePullPolicy: Always
          securityContext:
            runAsUser: 802
          ports:
            - containerPort: 8290
              protocol: TCP
            - containerPort: 9201
              protocol: TCP
            - containerPort: 9164
              protocol: TCP
          {{- if .Values.wso2.deployment.mi.synapseTest.enabled }}
            - containerPort: 9008
              protocol: TCP
          {{- end }}
          {{- if .Values.wso2.deployment.mi.envs }}
          env:
            {{- range $key, $val := .Values.wso2.deployment.mi.envs }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: wso2mi-conf
              mountPath: /home/wso2carbon/wso2-config-volume/conf
            - name: wso2mi-carbonapps
              mountPath: /home/wso2carbon/wso2mi-4.2.0/repository/deployment/server/carbonapps
      {{- if .Values.wso2.deployment.mi.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.wso2.deployment.mi.imagePullSecrets }}
      {{- else if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
        - name: wso2micro-integrator-deployment-creds
      {{ end }}
      volumes: 
        - name: wso2mi-conf
          configMap:
            name: {{ include "micro-integrator.fullname" . }}-conf
        - name: wso2mi-carbonapps
          persistentVolumeClaim:
            claimName: {{ include "micro-integrator.fullname" . }}-mi-carbonapps
